import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="w-1/6">
            {/* Contenido del slider */}
            <Sidebar />
          </div>
          <div className="w-5/6">
            {/* Contenido del otro componente */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
